final Map<String, List<String>> countryCities = {
  'Colombia': [
    'Barranquilla',
    'Bogotá',
    'Bucaramanga',
    'Cali',
    'Cartagena',
    'Cúcuta',
    'Manizales',
    'Medellín',
    'Pereira',
    'Santa Marta',
  ],
  'Alemania': [
    'Berlín',
    'Colonia',
    'Düsseldorf',
    'Frankfurt',
    'Hamburgo',
    'Múnich',
    'Stuttgart',
  ],
  'Argentina': [
    'Buenos Aires',
    'Córdoba',
    'La Plata',
    'Mar del Plata',
    'Mendoza',
    'Rosario',
    'Salta',
    'San Miguel de Tucumán',
    'Santa Fe',
  ],
  'Bolivia': [
    'Cochabamba',
    'La Paz',
    'Santa Cruz de la Sierra',
    'Sucre',
    'Tarija',
  ],
  'Brasil': [
    'Brasilia',
    'Curitiba',
    'Fortaleza',
    'Porto Alegre',
    'Recife',
    'Río de Janeiro',
    'Salvador',
    'São Paulo',
  ],
  'Canadá': [
    'Calgary',
    'Edmonton',
    'Montreal',
    'Ottawa',
    'Québec',
    'Toronto',
    'Vancouver',
  ],
  'Chile': [
    'Antofagasta',
    'Concepción',
    'Iquique',
    'La Serena',
    'Rancagua',
    'Santiago',
    'Temuco',
    'Valparaíso',
  ],
  'Ecuador': [
    'Ambato',
    'Cuenca',
    'Guayaquil',
    'Loja',
    'Machala',
    'Manta',
    'Quito',
  ],
  'España': [
    'Barcelona',
    'Bilbao',
    'Madrid',
    'Málaga',
    'Sevilla',
    'Valencia',
    'Zaragoza',
  ],
  'Estados Unidos': [
    'Chicago',
    'Dallas',
    'Houston',
    'Los Ángeles',
    'Miami',
    'Nueva York',
    'San Francisco',
    'Seattle',
  ],
  'Francia': [
    'Bordeaux',
    'Lille',
    'Lyon',
    'Marsella',
    'Niza',
    'París',
    'Toulouse',
  ],
  'Italia': [
    'Bolonia',
    'Florencia',
    'Milán',
    'Nápoles',
    'Roma',
    'Turín',
    'Venecia',
  ],
  'México': [
    'Cancún',
    'Chihuahua',
    'Ciudad de México',
    'Guadalajara',
    'León',
    'Mérida',
    'Monterrey',
    'Puebla',
    'Querétaro',
    'Tijuana',
  ],
  'Paraguay': [
    'Asunción',
    'Ciudad del Este',
    'Encarnación',
    'Pedro Juan Caballero',
  ],
  'Perú': [
    'Arequipa',
    'Chiclayo',
    'Cusco',
    'Iquitos',
    'Lima',
    'Piura',
    'Tacna',
    'Trujillo',
  ],
  'Uruguay': [
    'Maldonado',
    'Montevideo',
    'Paysandú',
    'Rivera',
    'Salto',
    'Tacuarembó',
  ],
  'Venezuela': [
    'Barquisimeto',
    'Caracas',
    'Cumaná',
    'Maracaibo',
    'Maracay',
    'Mérida',
    'Valencia',
  ],
};
